//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bidbwiki_local
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Description
    {
        public int desc_id { get; set; }
        public int post_ID { get; set; }
        public Nullable<int> user_ID { get; set; }

       [AllowHtml]
        public string Description_Text { get; set; }
        public Nullable<int> View_order { get; set; }
    
        public virtual Posts Posts { get; set; }
        public virtual Users Users { get; set; }
    }
}
