//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bidbwiki_local
{
    using System;
    using System.Collections.Generic;
    
    public partial class Images
    {
        public int img_id { get; set; }
        public Nullable<int> post_ID { get; set; }
        public string img_path { get; set; }
        public int View_order { get; set; }
    
        public virtual Posts Posts { get; set; }
    }
}
