//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bidbwiki_local
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bidbwikiEntities1 : DbContext
    {
        public bidbwikiEntities1()
            : base("name=bidbwikiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Description> Description { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<Posts> Posts { get; set; }
        public virtual DbSet<Profile_Pictures> Profile_Pictures { get; set; }
        public virtual DbSet<Reminders> Reminders { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
