//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bidbwiki_local
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminders
    {
        public int reminder_id { get; set; }
        public int user_ID { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
